# Generated by Django 4.1.7 on 2023-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=4)),
                ('course_number', models.CharField(max_length=4)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='tm_user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='tutor_me.course'),
        ),
    ]
