# Generated by Django 4.1.7 on 2023-03-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0002_course_tm_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
    ]
