# Generated by Django 4.1.6 on 2023-03-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0003_remove_course_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_user',
            name='courses',
        ),
    ]
