# Generated by Django 4.1.7 on 2023-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0004_remove_tm_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='tutor_me.course'),
        ),
    ]
