# Generated by Django 4.1.7 on 2023-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0005_tm_user_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=4)),
                ('courses', models.ManyToManyField(blank=True, to='tutor_me.course')),
            ],
        ),
    ]
