# Generated by Django 4.1.7 on 2023-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0006_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
