# Generated by Django 4.1.7 on 2023-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0008_tm_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='tutor_me.tm_user'),
        ),
    ]
