# Generated by Django 4.1.7 on 2023-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0009_course_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
