# Generated by Django 4.1.7 on 2023-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0010_dept_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tm_user',
            name='availability',
            field=models.ManyToManyField(blank=True, to='tutor_me.time_range'),
        ),
    ]
