# Generated by Django 4.1.7 on 2023-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0011_time_range_tm_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_range',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='time_range',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
