# Generated by Django 4.1.7 on 2023-04-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commenter',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='tutor_me.tm_user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
