# Generated by Django 4.1.7 on 2023-04-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0014_alter_review_commenter_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='commenter',
        ),
    ]
