# Generated by Django 4.1.7 on 2023-04-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0018_review_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='tutor_me.tm_user'),
        ),
    ]
