# Generated by Django 4.1.7 on 2023-04-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0019_alter_review_commenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='tutor_me.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='tutor_me.tm_user')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='tutor_me.time_range')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='tutor_me.tm_user')),
            ],
        ),
    ]
