# Generated by Django 4.1.6 on 2023-04-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0019_alter_review_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_user',
            name='calendar_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='calendar_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tm_user',
            name='calendar_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
