# Generated by Django 4.1.7 on 2023-04-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0020_booking'),
        ('tutor_me', '0020_tm_user_calendar_exists_tm_user_calendar_id_and_more'),
    ]

    operations = [
    ]
