# Generated by Django 4.1.7 on 2023-04-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0024_alter_friendrequest_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='friend_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_request', to='tutor_me.friendrequest'),
        ),
    ]
