# Generated by Django 4.1.7 on 2023-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0026_alter_friendrequest_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
